print("Go, team, go!")
print("You can do it.")
print()
print("Go, team, go!")
print("You can do it.")
print("You're the best,")
print("In the West.")
print("Go, team, go!")
print("You can do it.")
print()
print("Go, team, go!")
print("You can do it.")
print("You're the best,")
print("in the West.")
print("Go, team, go!")
print("You can do it.")
print()
print("Go, team, go!")
print("You can do it.")

